import pandas as pd
from langchain.llms import OpenAI

def generate_report(metrics_df, output_path, llm=None):
    if llm is None:
        llm = OpenAI(temperature=0)
    # 1. Sort post types by comment count
    metrics_df["comment_count"] = metrics_df["comment_count"].astype(int)
    sorted_df = metrics_df.sort_values("comment_count", ascending=False)
    table_md = sorted_df.to_markdown(index=False)
    # 2. LLM trend analysis
    prompt = f"""
    You are a social media analytics expert. Given the following comment counts by post type for @treehut's Instagram in March 2025, provide a trend analysis:
    - Which post types received the most and least engagement?
    - What are the most consistently engaging post types?
    - Suggest 3–5 new or emerging post types @treehut should consider highlighting next.
    
    Data (Markdown table):
    {table_md}
    
    Write a summary of your analysis and provide evidence. Then provide a list of 3-5 new or emerging post types @treehut should consider highlighting next.
    """
    analysis = llm(prompt).strip()
    # 3. Write Markdown report
    with open(output_path, "w") as f:
        f.write("# @treehut Instagram Post Type Analysis — March 2025\n\n")
        f.write("## Executive Summary\n\n")
        f.write(analysis + "\n\n")
        f.write("## Comment Count by Post Type\n\n")
        f.write(table_md + "\n")
        f.write("\n---\n_Report generated by LLM using LangChain and OpenAI.\n")
