import pandas as pd
from langchain.llms import OpenAI

def generate_report(metrics_df, output_path, llm=None):
    if llm is None:
        llm = OpenAI(temperature=0)
    # 1. Top 10 topics by total engagement
    topic_totals = metrics_df.groupby("topic")["engaged_users"].sum().sort_values(ascending=False)
    top_topics = topic_totals.head(10).index.tolist()
    top_df = metrics_df[metrics_df["topic"].isin(top_topics)]
    # 2. Summarize as Markdown table
    table_md = top_df.pivot_table(index="date", columns="topic", values="engaged_users", fill_value=0).to_markdown()
    # 3. LLM trend analysis
    prompt = f"""
    You are a social media analytics expert. Given the following daily engagement data for @treehut's Instagram, provide a concisetrend analysis:
    - Which topics gained or lost traction over time?
    - What are the most consistently engaging topics?
    - Suggest 3–5 new or emerging topics @treehut should consider highlighting next.
    
    Data (Markdown table):
    {table_md}
    
    Write a summary of your analysis and provide evidence. Then provide a list of 3-5 new or emerging topics @treehut should consider highlighting next.
    """
    analysis = llm(prompt).strip()
    # 4. Write Markdown report
    with open(output_path, "w") as f:
        f.write("# @treehut Instagram Trend Analysis — March 2025\n\n")
        f.write("## Executive Summary\n\n")
        f.write(analysis + "\n\n")
        f.write("## Engagement by Topic and Date (Top 10 Topics)\n\n")
        f.write(table_md + "\n")
        f.write("\n---\n_Report generated by LLM using LangChain and OpenAI.\n")
